const tasksData = [
  {
    id: 1,
    room: "101",
    task: "Regular Cleaning",
    floor: "1st Floor",
    priority: "Medium",
    status: "Pending",
    staff: "Sunita",
    time: "09:00 AM",
    updated: "5 mins ago",
  },
  {
    id: 2,
    room: "102",
    task: "Deep Cleaning",
    floor: "1st Floor",
    priority: "High",
    status: "In Progress",
    staff: "Anita",
    time: "09:15 AM",
    updated: "2 mins ago",
  },
  {
    id: 3,
    room: "103",
    task: "Linen Change",
    floor: "1st Floor",
    priority: "Low",
    status: "Completed",
    staff: "Pooja",
    time: "08:45 AM",
    updated: "15 mins ago",
  },
  {
    id: 4,
    room: "104",
    task: "Bathroom Cleaning",
    floor: "1st Floor",
    priority: "High",
    status: "Delayed",
    staff: "Ramesh",
    time: "10:00 AM",
    updated: "25 mins ago",
  },
  {
    id: 5,
    room: "105",
    task: "Mini Bar Refill",
    floor: "1st Floor",
    priority: "Low",
    status: "Emergency",
    staff: "Meena",
    time: "10:30 AM",
    updated: "1 min ago",
  },
  {
    id: 6,
    room: "201",
    task: "Regular Cleaning",
    floor: "2nd Floor",
    priority: "Medium",
    status: "Pending",
    staff: "Rahul",
    time: "11:00 AM",
    updated: "8 mins ago",
  },
  {
    id: 7,
    room: "202",
    task: "Linen Change",
    floor: "2nd Floor",
    priority: "Low",
    status: "Completed",
    staff: "Sneha",
    time: "09:40 AM",
    updated: "18 mins ago",
  },
  {
    id: 8,
    room: "203",
    task: "Deep Cleaning",
    floor: "2nd Floor",
    priority: "High",
    status: "Pending",
    staff: "Akash",
    time: "12:00 PM",
    updated: "12 mins ago",
  },
  {
    id: 9,
    room: "204",
    task: "Bathroom Cleaning",
    floor: "2nd Floor",
    priority: "Medium",
    status: "In Progress",
    staff: "Priya",
    time: "01:15 PM",
    updated: "6 mins ago",
  },
  {
    id: 10,
    room: "205",
    task: "Mini Bar Refill",
    floor: "2nd Floor",
    priority: "Low",
    status: "Completed",
    staff: "Vikas",
    time: "02:00 PM",
    updated: "30 mins ago",
  },
  {
    id: 11,
    room: "301",
    task: "Regular Cleaning",
    floor: "3rd Floor",
    priority: "Medium",
    status: "Pending",
    staff: "Sunita",
    time: "09:00 AM",
    updated: "10 mins ago",
  },
  {
    id: 12,
    room: "302",
    task: "Deep Cleaning",
    floor: "3rd Floor",
    priority: "High",
    status: "Emergency",
    staff: "Anita",
    time: "11:30 AM",
    updated: "3 mins ago",
  },
  {
    id: 13,
    room: "303",
    task: "Window Cleaning",
    floor: "3rd Floor",
    priority: "Low",
    status: "Completed",
    staff: "Pooja",
    time: "08:30 AM",
    updated: "20 mins ago",
  },
  {
    id: 14,
    room: "304",
    task: "Bathroom Cleaning",
    floor: "3rd Floor",
    priority: "High",
    status: "Delayed",
    staff: "Rahul",
    time: "12:30 PM",
    updated: "40 mins ago",
  },
  {
    id: 15,
    room: "305",
    task: "Mini Bar Refill",
    floor: "3rd Floor",
    priority: "Medium",
    status: "Pending",
    staff: "Sneha",
    time: "03:00 PM",
    updated: "5 mins ago",
  },
  {
    id: 16,
    room: "401",
    task: "Regular Cleaning",
    floor: "4th Floor",
    priority: "Medium",
    status: "Completed",
    staff: "Akash",
    time: "08:00 AM",
    updated: "50 mins ago",
  },
  {
    id: 17,
    room: "402",
    task: "Deep Cleaning",
    floor: "4th Floor",
    priority: "High",
    status: "Pending",
    staff: "Priya",
    time: "10:15 AM",
    updated: "9 mins ago",
  },
  {
    id: 18,
    room: "403",
    task: "Linen Change",
    floor: "4th Floor",
    priority: "Low",
    status: "In Progress",
    staff: "Vikas",
    time: "11:20 AM",
    updated: "7 mins ago",
  },
  {
    id: 19,
    room: "404",
    task: "Bathroom Cleaning",
    floor: "4th Floor",
    priority: "Medium",
    status: "Completed",
    staff: "Meena",
    time: "01:00 PM",
    updated: "14 mins ago",
  },
  {
    id: 20,
    room: "405",
    task: "Mini Bar Refill",
    floor: "4th Floor",
    priority: "Low",
    status: "Pending",
    staff: "Ramesh",
    time: "02:20 PM",
    updated: "4 mins ago",
  }
];

export default tasksData;